### ISSUE TITLE
Migrate UCI Chatbot helper from GraphQL to Prisma etc. and use SQL queries

### ISSUE THREAD

**Issue by tushar5526** [Mission-Prerna/uci-chatbot-helper#16]
https://github.com/Mission-Prerna/uci-chatbot-helper uses GraphQL to run segment queries. Migrate to using SQL as we have deprecated GraphQL

**Comment by tushar5526** [comment]
@Ajay-Maury to deploy uci-chatbot-helper on staging and @AakashSatpute119 to test on dev.

**Comment by AakashSatpute119** [comment]
**BUGS**

- [ ] 1. Chatbots are not working getting a Network error toast message -https://prnt.sc/U4Iw3vz9CKp2 
- [ ] 2. Upload media is failing on UCI unable to create bot - https://prnt.sc/DWKBANCxHrL0

**Comment by AakashSatpute119** [comment]
@karntrehan  share new build with new ips.

**Comment by AakashSatpute119** [comment]
APK (ip change build): https://drive.google.com/open?id=1ApseD185292z_afOI7QcMOj50YcYCAZs&usp=drive_copy 
Old flow is working fine tested with last shared Apk.

**Comment by dhruv-1001** [comment]
To be deployed on prod.

**Comment by karntrehan** [comment]
Release Getting tracked in https://github.com/Mission-Prerna/prerna-lakshya-app/issues/486
