### ISSUE TITLE
[RCA] Notifications not working for Samwad since Feb 22nd

### ISSUE THREAD

**Issue by karntrehan** [Mission-Prerna/uci-chatbot-helper#17]
Users were not recieving notification on prod since 22nd feb. This was fixed last week. We should create an RCA with detailed analysis.

**Comment by rohitsamagra** [comment]
- Karan to discuss with Kishan

**Comment by rohitsamagra** [comment]
- Karan to calculate the MAU and look at it how many of them do we have tokens for and how many were able to receive

**Comment by karntrehan** [comment]
To review and share: https://docs.google.com/document/d/1YXqZxI9WVn2eIgGa5RwzqmWVkvxslz54x-3P7aXqpyw/edit#heading=h.df3v4ge5d6s2

**Comment by rohitsamagra** [comment]
- Create a seperate ticket to increase notification delivery for users 
- Karan to update numbers as part of this ticket

**Comment by karntrehan** [comment]
RCA Shared
