### ISSUE TITLE
[Ad Hoc] UCI Admin UI Changes

### ISSUE THREAD

**Issue by karntrehan** [Mission-Prerna/uci-chatbot-helper#23]
Changes: 

- [x] Create broadcast bot rename to "Notify user"
- [x] Segment Id rename to "Segment"
- [x] Recipient list - To be added to the right of segment name and make an "or"
- [x] End date - On selection show the exact time of the end date.
- [x] Add Simplified conversation Logic  rename to "Create bot"
- [x] Content rename to "Bot Content to show to user"

**Comment by ankitmlesmagico** [comment]
above updated are updated on staging

**Comment by karntrehan** [comment]
@rohitsamagra to test.

**Comment by charanpreet-s** [comment]
Tested on staging

**Comment by VargishChauhan** [comment]
Tested on Prod by @AakashSatpute119
