### ISSUE TITLE
(Samwad)Creating segment within Samwad Admin Panel

### ISSUE THREAD

**Issue by karntrehan** [Mission-Prerna/uci-chatbot-helper#28]
As an admin I can send an outbound message to all teachers or geographical segments.

- [ ] 1. There should be an option to select one or more actor(teacher, mentor and Examiner)
- [ ] 2.   There should be an option to select **ALL** options with a single check. Also, if i uncheck **ALL** option , then all options should be unchecked.
- [ ] 3. Scrolling should be supported in the page,  as well as sub section (district , block etc.) to easily view and select all options 
- [ ] 4. Options inside District , block and school should be alphabetically ordered

Refer to the 4th point of PRD and mockups

https://docs.google.com/document/d/1YDa282_wqMBW2XipiMEecck0ivroh9QPkyUGEkwSIJo/edit

## UCI FE
- [ ] Give an option to user to create segment
- [ ] On clicking open modal as shown above
- [ ] Make API call to NL BE for actors and display in modal
- [ ] On actor selection make API call to NL BE for districts and display in modal
- [ ] Similarly for blocks and schools
- [ ] Once user selects done, make create-segment API call to NL BE

## NL BE
- [ ] Expose API for actors, districts, blocks and schools
- [ ] Build create-segment API for geographic actor specific segmentation

**Comment by karntrehan** [comment]
## Get segment filters

API: 
`@GET(/segment-filters)`

Query Params:
* `actors=-1` or `actors=1,2,3` (actor_ids)
* `districts=-1` or `districts=1,2` (district_ids)
* `blocks=-1` or `blocks=1,2` (block_ids)
* `schools=-1` or `schools=U1,U2` (udises)

^ All optional

Response: 

```json
{
  "actors": [
    {
      "id": "1",
      "label": "Teacher"
    },
    {
      "id": "2",
      "label": "Mentor"
    }
  ],
  "districts": [
    {
      "id": "1",
      "label": "Agra"
    },
    {
      "id": "2",
      "label": "Unao"
    }
  ],
  "blocks": [
    {
      "id": "1",
      "label": "Aaspur Devsara"
    },
    {
      "id": "2",
      "label": "Abholi"
    }
  ],
  "schools": [
    {
      "id": "9430702904",
      "label": "P S VAJEERPUR"
    },
    {
      "id": "09112900802",
      "label": "Local Body (Basic Shiksha Paraishad )"
    }
  ]
}
```

**Comment by karntrehan** [comment]
## Create segment

API:
`@POST(/segment-filters/create)`

Body: 
```json
{
  "actors": "1",
  "districts": "3,7",
  "blocks": "9,10,21,11",
  "schools": "U1,U8,U9",
  "name": "Segment for teacher training",
  "description": "Segment for teacher training"
}
```

```json
{
  "actors": "1,9",
  "districts": "3,7",
  "blocks": "9,10,21,11",
  "schools": "-1",
  "name": "Segment for teacher training All schools",
  "description": "Segment for teacher training"
}
```

^ All mandatory

Response: 

```json
{
  "segment_id": 1
}
```

```json
{
  "error_code": "",
  "error_message": ""
}
```

**Comment by Ajay-Maury** [comment]
For API:  @POST(/segment-filters/create)

- Is it for the actor as Examiner also, if yes fetching mentors  based on district ID and block ID (optional)
- In the case of the actor as Mentor or Diet Mentor,  fetching mentors based on district ID and block ID (optional)
- In the case of the actor as a Teacher, 
   - if schools are not empty then fetching mentors based on district, block, and udise in `teacher_school_list_mapping`
   - if schools are empty, fetching mentors based on district ID and block ID (optional)


and in the API body payload expecting `actors` , `districts` , `blocks` , and `schools` as an array instead of comma-separated string

cc:- @karntrehan

**Comment by AakashSatpute119** [comment]
- Demo call to schedule tommorow.

**Comment by karntrehan** [comment]
Release getting tracked in https://github.com/Mission-Prerna/prerna-lakshya-app/issues/486
