### ISSUE TITLE
[BE] Create API to give count in segment

### ISSUE THREAD

**Issue by karntrehan** [Mission-Prerna/uci-chatbot-helper#3]
Expose a `/segments/{segment-id}/mentors/count` endpoint that returns the count of members in the passed `segment-id` & mentors have tokens. Format of response: 

```
{
  "totalCount": 23123
}
```

**Comment by karntrehan** [comment]
PR Raised: https://github.com/Mission-Prerna/uci-chatbot-helper/pull/4

**Comment by karntrehan** [comment]
`http://103.154.251.109:8070/segments/3/mentors/count` giving `{"statusCode":404,"message":"Cannot GET /segments/3/mentors/count","error":"Not Found"}`. @choxx can you check please.

**Comment by yuvrajsab** [comment]
@karntrehan i can check this if i can get access to the server

**Comment by choxx** [comment]
The current route path is: `http://103.154.251.109:8070/segments/3/mentors-count`.
There was a typo in the main PR, in which I fixed the route convention to `/segments/:id/mentors-count` from `/segments/3/count`. However, I missed that the required path was: `/segments/{segment-id}/mentors/count `.

![Image](https://user-images.githubusercontent.com/11666456/235505850-53196b77-6526-4cf8-a3cf-b37b2f3dbfc4.png)

**Comment by choxx** [comment]
Patched the endpoint to: `GET /segments/:id/mentors/count`
