### ISSUE TITLE
Enabling scheduling of bots - Enhancements

### ISSUE THREAD

**Issue by VargishChauhan** [Mission-Prerna/uci-chatbot-helper#31]
As a admin, when i  schedule a bot and want to make changes to it with respect to time, segment or content. I should be able to do that

Scope:
- [ ] I should be  able to delete the bot if bot is not triggered

Out of scope

~- [ ] I should be  able to update the time of the scheduled bot if bot is not triggered~
~- [ ] I should be  able to update the content if bot is not triggered~
~- [ ] I should be able to  update segment for already created bot if bot is not triggered~

**Comment by karntrehan** [comment]
Getting tracked in https://github.com/Mission-Prerna/prerna-lakshya-app/issues/486
