### ISSUE TITLE
[Bug] Samvad Dashboard not showing up on Metabase

### ISSUE THREAD

**Issue by VargishChauhan** [Mission-Prerna/uci-chatbot-helper#35]
Program team are facing an issue with the following views
Teachers who have accessed NS
Mentors who have accessed NS
Users on different App versions
Bot level tracking (Priority for PT to understand adoption/engagement with different messages)

**Comment by karntrehan** [comment]
**Teacher assessments (Unique students)**
Dashboard - 13L
API - 1.3L 

**Spot assessments - Mentor (Unique students)**
Dashboard - 3L
API - 1.2L

**Comment by karntrehan** [comment]
Fix undertaken to limit data for 6 months only. Long term fix of deleting data older than 6 months to be picked in next sprint.
