### ISSUE TITLE
(Samwad Analytics) [Bug]  Issue with Bot level tracking

### ISSUE THREAD

**Issue by VargishChauhan** [Mission-Prerna/uci-chatbot-helper#37]
In Samwad Dashboard,  
For Bot Level tracking , Latest data i can see is of May 2024. Given that Program team has sent many messages in August 2024, those messages are being shown without date in dashboard.

Refer to the screenshot for issue

![Image](https://github.com/user-attachments/assets/01f49ec3-3ae1-4818-9b20-2e4719e69558)

Metabase :  [Link](http://128.199.28.17:54522/dashboard/2-nipun-samwad-dashboard)

**Comment by AakashSatpute119** [comment]
- @Ajay-Maury  to add issue description here

**Comment by VargishChauhan** [comment]
Two issues identified.
NL -Mentor and others was not syncing - resolved
Clickhouse data - Not syncing - WIP

 On closed and another WIP

**Comment by dhruv-1001** [comment]
@dhruv-1001 to review PR.

**Comment by VargishChauhan** [comment]
Working fine
